spring:
  application:
    name: cadastro
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD_EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true